<?php 
  $mysql_connect = array
  (
    //"host" 			=> "mail.ksc.ru",
    "host_db" 			=> "db.ksc.loc",
    "host_cloud"		=> "cloud.ksc.ru",
	"user"			=> "addr_syncer",
	"pass"			=> "JEGuVoRE",
	"db_mail"		=> "mail",
	"db_cloud"		=> "nextcloud",
	"tbl_src" 		=> "addressbook_all_with_aliases",
	"tbl_src_2" 		=> "auth",
	"tbl_dst" 		=> "oc_cards",
	"tbl_dst_2" 		=> "oc_cards_properties",
	"tbl_dst_3" 		=> "oc_addressbookchanges",
	"tbl_dst_4" 		=> "oc_addressbooks"
  );
?>